blog/urls.py
from django.urls import path

from .views import PostDetailView, PostListView

app_name = 'blog'
urlpatterns = [
    path('<int:pk>/', PostDetailView.as_view(), name='detail'),
    path('', PostListView.as_view(), name='list'),
]

myblog/urls.py
from django.contrib import admin
from django.urls import path, include

from blog.feeds import RssSiteNewsFeed, AtomSiteNewsFeed

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('rss/', RssSiteNewsFeed()),
    path('atom/', AtomSiteNewsFeed())

]

blog/models.py
import re

import markdown
from django.db import models


# Create your models here.


class Post(models.Model):
    """
    文章
    """
    title = models.CharField(max_length=100, default='', verbose_name='题目')
    content = models.TextField(verbose_name='正文')
    html = models.TextField(verbose_name='正文html', blank=True, null=True)
    toc = models.TextField(verbose_name='目录', blank=True, null=True)
    author = models.ForeignKey('Author', on_delete=models.CASCADE, verbose_name='作者')
    tags = models.ManyToManyField('Tag', verbose_name='标签', blank=True)
    category = models.ForeignKey('Category', verbose_name='分类', on_delete=models.CASCADE, blank=True, null=True)
    excerpt = models.TextField(verbose_name='摘要', blank=True, null=True)

    create_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    last_update_time = models.DateTimeField(auto_now=True, verbose_name='最后更新时间')

    def save(self, *args, **kwargs):
        md = markdown.Markdown(extensions=['markdown.extensions.extra', 'markdown.extensions.codehilite',
                                           'markdown.extensions.toc'])
        regex = re.compile('(.*)<!--more-->', re.DOTALL)
        result = regex.match(self.content)
        if result:
            self.excerpt = md.convert(result.group(1))
        else:
            self.excerpt = ''
        self.html = md.convert(self.content)
        self.toc = md.toc
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('-last_update_time',)


class Author(models.Model):
    """
    作者
    """
    name = models.CharField(max_length=100, default='', verbose_name='名字')
    email = models.EmailField(verbose_name='邮箱')
    age = models.IntegerField(verbose_name='年龄', null=True, blank=True)
    birthday = models.DateField(verbose_name='生日', null=True, blank=True)

    def __str__(self):
        return self.name


class Comment(models.Model):
    """
    评论
    """
    name = models.CharField(max_length=100, verbose_name='名字')
    email = models.EmailField(verbose_name='邮箱')
    content = models.TextField(verbose_name='内容')
    post = models.ForeignKey('Post', on_delete=models.CASCADE, verbose_name='文章')

    def __str__(self):
        return self.name


class Tag(models.Model):
    """
    标签
    """
    name = models.CharField(max_length=100, verbose_name='标签')

    def __str__(self):
        return self.name


class Category(models.Model):
    """
    分类
    """
    name = models.CharField(max_length=100, verbose_name='分类')

    def __str__(self):
        return self.name

blog/views.py
from django.shortcuts import render
from django.views.generic import DetailView, ListView

from .models import Post


# Create your views here.

class PostDetailView(DetailView):
    template_name = 'detail.html'
    model = Post


class PostListView(ListView):
    template_name = 'index.html'
    model = Post
    queryset = Post.objects.all()

blog/templates/detail.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap-4.1.3/bootstrap.min.css' %}">
{#    <link rel="stylesheet" href="{% static 'styles/tomorrow-night.css' %}">#}
{#    <script type="text/javascript" src="{% static 'highlight.pack.js' %}"></script>#}
{#    <script type="text/javascript">hljs.initHighlightingOnLoad();</script>#}
    <link rel="stylesheet" href="{% static 'css/highlight/emacs.css' %}">
    <title>{{ post.title }}</title>
</head>
<body>

<div class="container">
    <p>{{ post.toc | safe }}</p>
    <h1>{{ post.title }}</h1>
    <p>{{ post.content }}</p>
    <p>{{ post.html | safe }}</p>

</div>
{#   <div class="row">#}
{#       <div class="col-sm-3">.col</div>#}
{#       <div class="col-sm-3">.col</div>#}
{#       <div class="col-sm-3">.col</div>#}
{#   </div>#}
{#  <div class="container">#}
{#      <h1>hello<mark> world</mark></h1>#}
{#      <p> test <abbr title="title">flae</abbr></p>#}
{#  </div>#}
{#    <div class="container">#}
{#        <p>kfale:#}
{#        <blockquote class="blockquote">#}
{#           <p>fekfalel</p>#}
{#           <footer class="blockquote-footer">lfa</footer>#}
{#        </blockquote>#}
{#        </p>#}
{#    </div>#}

{#    <div class="container">#}
{#        <d1>#}
{#            <dt>coffee</dt>#}
{#            <dd>blank</dd>#}
{#            <dt>mik</dt>#}
{#            <dd>lfe;a</dd>#}
{#        </d1>#}
{#    </div>#}
{#    <div class="container">#}
{#        <code>flea</code><br/>#}
{#        <kbd>fke</kbd>#}
{#        <pre>glrs</pre>#}
{#    </div>#}
{#    <div class="container">#}
{#        <p class="text-info">info</p>#}
{#        <p class="text-success">success</p>#}
{#        <p class="text-primary">primary</p>#}
{#        <p class="text-danger">danger</p>#}
{#        <p class="text-warning">warning</p>#}
{#    </div>#}
{#    <div class="container">#}
{#        <a href="#" class="text-success">fek</a>#}
{#    </div>#}
{#    <div class="container">#}
{#        <p class="bg-dark text-white">#}
{#            hello#}
{#        </p>#}
{#    </div>#}
{#    <div class="table-responsive">#}
{#        <table class="table">#}
{#            <thead>#}
{#              <tr>#}
{#                <th>#</th>#}
{#                <th>Firstname</th>#}
{#                <th>Lastname</th>#}
{#                <th>Age</th>#}
{#                <th>City</th>#}
{#                <th>Country</th>#}
{#                <th>Sex</th>#}
{#                <th>Example</th>#}
{#                <th>Example</th>#}
{#                <th>Example</th>#}
{#                <th>Example</th>#}
{#              </tr>#}
{#            </thead>#}
{#            <tbody>#}
{#              <tr>#}
{#                <td>1</td>#}
{#                <td>Anna</td>#}
{#                <td>Pitt</td>#}
{#                <td>35</td>#}
{#                <td>New York</td>#}
{#                <td>USA</td>#}
{#                <td>Female</td>#}
{#                <td>Yes</td>#}
{#                <td>Yes</td>#}
{#                <td>Yes</td>#}
{#                <td>Yes</td>#}
{#              </tr>#}
{#            </tbody>#}
{#        </table>#}
{#    </div>#}
{#    <div class="jumbotron jumbotron-fluid">#}
{#  <div class="container">#}
{#      <h1>feaf</h1>#}
{#      <p>fkeaf</p>#}
{#  </div>#}
{#</div>#}

{#<div class="container">#}
{#    <div class="alert alert-success alert-dismissible">#}
{#        <button type="button" class="close" data-dismiss="alert">&times;</button>#}
{#        <strong>success</strong>#}
{#    </div>#}
{#</div>#}

{#<p>test</p>#}
{#<div class="codehilite"><pre><span></span><span class="k">def</span> <span class="nf">hello</span><span class="p">(</span><span class="bp">self</span><span class="p">):</span>#}
{#    <span class="k">print</span><span class="p">(</span><span class="s1">&#39;hello&#39;</span><span class="p">)</span>#}
{#</pre></div>#}
{##}
{##}
{#<div class="codehilite"><pre><span></span>pip install django#}
{#</pre></div>#}


<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="{% static 'js/bootstrap-4.1.3/bootstrap.min.js' %}"></script>
</body>
</html>

blog/templates/index.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/bootstrap-4.1.3/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/highlight/emacs.css' %}">
    <title>my blog</title>
</head>
<body>
<div class="container">
    {% for post in post_list %}
    <div>
        <a href="{% url 'blog:detail' post.pk %}" class="text-dark"><h2 class="text-center">{{ post.title }}</h2></a>
        <p>{{ post.excerpt | safe }}</p>
        <a href="{% url 'blog:detail' post.pk %}" class="text-dark">查看全文</a>


    </div>
    {% endfor %}

</div>

</body>
</html>